/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#ced3d7",
        background: "#f9f9fc",
        "on-tertiary-fixed-variant": "#43474b",
        "secondary-fixed-dim": "#7edb7f",
        outline: "#727784",
        "inverse-primary": "#adc7ff",
        "on-secondary-fixed": "#002105",
        "surface-container-high": "#e8e8ea",
        "on-surface": "#1a1c1e",
        "on-secondary-fixed-variant": "#005316",
        "on-primary-container": "#bfd2ff",
        "tertiary-fixed-dim": "#c3c7cb",
        "on-background": "#1a1c1e",
        primary: "#0057B8",
        "on-primary": "#ffffff",
        "primary-fixed": "#d8e2ff",
        "on-primary-fixed": "#001a41",
        "on-secondary-container": "#0b7225",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f0f0f3",
        "on-surface-variant": "#424752",
        "surface-container-highest": "#e2e2e5",
        "on-error-container": "#93000a",
        "primary-container": "#0057B8",
        "surface-container": "#eeeef0",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#adc7ff",
        "tertiary-container": "#565b5e",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#99f899",
        tertiary: "#3f4447",
        "secondary-container": "#97f596",
        "surface-dim": "#dadadc",
        "surface-variant": "#e2e2e5",
        "surface-tint": "#0d5bbc",
        "surface-container-low": "#f3f3f6",
        surface: "#f9f9fc",
        "on-tertiary-fixed": "#171c1f",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#004493",
        "surface-bright": "#f9f9fc",
        "outline-variant": "#c2c6d4",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2f3133",
        secondary: "#016e21",
        "tertiary-fixed": "#dfe3e7",
        error: "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Public Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
};
